main:
- name: Research
  url: /research/
  weight: 10
- name: Teaching
  url: /teaching/
  weight: 30
- name: INEGI data
  url: /#inegi
  weight: 35
- name: Contact
  url: /#contact
  weight: 50
- name: CV
  url: /uploads/resume.pdf
  weight: 60
