appearance:
  theme_day: job-market
  theme_night: ""
  font: Roboto
  font_size: m
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: Bonang N. Seoela, Economics Ph.D. candidate at Indiana University
      Bloomington. Research in international trade, environmental policy, and energy
      economics.
    twitter: BSeoela
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: google-site-verification=dLr2DgddgF6-AX93syrDKvdttFVx9EBM0chw3bYUU_o
    baidu: ''
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true
footer:
  copyright:
    notice: "\xA9 {year} Bonang N. Seoela"
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
locale:
  date_format: Jan 2, 2006
  time_format: 3:04 PM
  address_format: en-us
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: https://github.com/<username>/<repository>
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
security:
  allow_frame: true
